name: Python CI

on:
  push:
    paths:
      - 'macrobase_py/**'
      - 'pyproject.toml'
      - '.pre-commit-config.yaml'
      - '.github/workflows/python.yml'
  pull_request:
    paths:
      - 'macrobase_py/**'
      - 'pyproject.toml'
      - '.pre-commit-config.yaml'
      - '.github/workflows/python.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch pre-commit
          hatch env create
          hatch run pip install -e .
      - name: Run pre-commit
        run: |
          hatch run pre-commit run --all-files
      - name: Run tests
        run: |
          hatch run pytest
